---
title: "user_interface"
output: html_document
runtime: shiny
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library interface

```{r echo=FALSE}
# Import eric interface
library(stringr)
library(purrr)
library(ggplot2)
library(knitr)
library(shiny)
library(miniUI)
library(magrittr)
library(plotly)
```

We pull in our eric functions from eric_interface.Rmd
````{r}
source(knitr::purl("data-backend.Rmd", output = tempfile(), quiet = TRUE))
```



## Inputs and Outputs

Term groups are comma deliminated, and newline separated
For example:

> foo, bar
>
> foobie

is interpreted as

> ("foo" OR "bar") AND ("foobie")


Just a button that executes a hard coded ERIC search query, which is then displayed below


## UI Helper functions
```{r echo=FALSE}
plot_size <- 160
```


## Input Panel
```{r echo=FALSE}

empty_space_string <- "--"

terms <- list()

translate_binary_to_label <- function(binary, sym) {
  sym_holder <- sym
  present_vars <- c()
  binary_vars <- str_split(binary, pattern = " ", simplify = TRUE)

  for (i in 1:length(binary_vars)) {
    if (binary_vars[i] == "1") {
      present_vars %<>% append(sym[i])
    }
  }

  return(paste0(present_vars, collapse = " OR "))
}
translate_binary_to_label <- Vectorize(translate_binary_to_label)

create_summary_graph_alt <- function(explor, set) {
  set %<>% str_split(" OR ", simplify = TRUE)

  data <- explor %>%
    summarise(set_a = paste(!!!syms_a), eric) %>%
    mutate(set_a = translate_binary_to_label(set_a, list(set)))

  plot <- data %>%
    ggplot(aes(x = set_a, y = eric)) +
    geom_bar(stat = "identity") +
    scale_y_log10(
      n.breaks = 10,
      labels = scales::label_number()
    ) +
    theme(axis.text.x = element_text(size = 10, angle = 45, hjust = 0))

  return(plot)
}

create_heatmap <- function(explor, setA, setB) {
  setA %<>% str_split(" OR ", simplify = TRUE)
  setB %<>% str_split(" OR ", simplify = TRUE)

  set_a_syms <- map(setA, sym)
  set_b_syms <- map(setB, sym)

  # find the names of terms we're not using
  other_names <- explor %>%
    select(
      -as.vector(setA),
      -as.vector(setB),
      -eric, -query, -proquest
    ) %>%
    names()

  if (length(other_names) > 1) {
    # filter to only where the terms we're not using are 0
    explor %<>%
      filter_at(vars(other_names), all_vars(. == 0)) %>%
      select(-other_names)
  }

  # process as if we only have two terms
  heat_data <- explor %>%
    summarize(set_a = paste(!!!set_a_syms), set_b = paste(!!!set_b_syms), eric) %>%
    mutate(
      set_a = translate_binary_to_label(set_a, list(setA)),
      set_b = translate_binary_to_label(set_b, list(setB))
    )

  # make the heatmap
  heat_plot <- heat_data %>%
    ggplot(aes(set_a, set_b, fill = eric)) +
    geom_tile() +
    labs(x = NULL, y = NULL) +
    theme(
      axis.text.x = element_text(size = 15, vjust = 0.5, angle = 45),
      axis.text.y = element_text(size = 15)
    )

  return(heat_plot)
}

create_summary <- function(explor, setA) {
  setA %<>% str_split(" OR ", simplify = TRUE)

  set_a_syms <- map(setA, sym)

  # find the names of terms we're not using
  other_names <- explor %>%
    select(
      -as.vector(setA),
      -eric, -query, -proquest
    ) %>%
    names()

  # filter to only where the terms we're not using are 0
  explor %<>%
    filter_at(vars(other_names), all_vars(. == 0)) %>%
    select(-other_names)

  # process as if we only have two terms
  data <- explor %>%
    summarize(set_a = paste(!!!set_a_syms), eric) %>%
    mutate(set_a = translate_binary_to_label(set_a, list(setA)))

  # make the summary
  plot <- ggplot(data, aes(x = set_a, y = eric)) +
    geom_bar(stat = "identity") +
    scale_y_log10(
      n.breaks = 10,
      labels = scales::label_number()
    ) +
    labs(x = NULL) +
    theme(axis.text.x = element_text(size = 10, angle = 45, vjust = 0))

  return(plot)
}
```

```{r eval=FALSE}
withProgress(message = "Searching ERIC\n", value = 0, {
  # Number of times we'll go through the loop
  n <- length(formatted_products)

  for (i in 1:n) {
    url <- create_eric_url(formatted_products[[i]], rows = 20, fields = options)

    eric_responses[[i]] <- get_eric_json(url)

    # Increment the progress bar, and update the detail text.
    incProgress(1 / n, detail = url)
  }
})
```

```{r echo=FALSE}


create_ui_gadget <- function() {
  get_css <- function() {
    return("div {
            padding-top: 10px;
            padding-left: 10px;
            padding-right: 10px;
            padding-bottom: 10px;
           }")
  }

  num_found_for_terms <- list()

  compare_count <- 1

  summary_count <- 1

  # Define UI
  ui <- miniUI::miniPage(
    miniTabstripPanel(miniTabPanel(
      "Search",

      # Sidebar layout with input and output definitions
      # Input for terms and options
      fillCol(
        wellPanel(
          textInput("terms1", "Term Set", value = "FAA, Part 147"),
          actionButton("add_term_set", "Add Term Set", class = "btn-success"),
          wellPanel(
            tags$h4("Options"),
            checkboxInput("peer", "Peer Reviewed", value = FALSE),
            radioButtons(
              "database", "Database: ",
              c(
                "ERIC" = "eric",
                "ProQuest" = "proquest"
              )
            )
          ),
          actionButton("search", "Search", class = "btn-success"),
          br(),
        )
      )
    ), miniTabPanel(
      "Summary",
      fillCol(
        wellPanel(
          plotOutput("summary_graph")
        )
      )
    ), miniTabPanel(
      "Comparison",
      fillCol(
        wellPanel(
          plotOutput("comparison_graph")
        )
      )
    ))
  )

  server <- function(input, output, session) {
    get_input_terms <- function(input, number_input_boxes) {
      terms_list <- list()

      sapply(1:number_input_boxes, function(x) {
        terms_list[[length(terms_list) + 1]] <<- input[[paste0("terms", x)]]
      })

      return(terms_list)
    }
    add_term_set <- function(number_input_boxes, value = "") {
      input_box <- textInput(paste0("terms", number_input_boxes + 1), "", value = value)

      insertUI(
        selector = paste0("#terms", number_input_boxes),
        where = "afterEnd",
        ui = input_box
      )

      return(number_input_boxes + 1)
    }


    number_input_boxes <- 1

    number_input_boxes <- add_term_set(number_input_boxes, value = "Pandemic, Covid-19")

    observeEvent(input$add_term_set, {
      number_input_boxes <<- add_term_set(number_input_boxes)
    })

    observeEvent(input$search, {
      # Test search
      # test_explor <- group_to_explor(make_queries_for_group(set_to_group(make_set("E OR F OR G"), make_set("C OR D"))))

      explor <- test_eric_explor_b

      output$summary_graph <- renderPlot(create_summary(explor, "C OR D"))

      output$comparison_graph <- renderPlot(create_heatmap(explor, setA = "E OR F OR G", setB = "C OR D"))

      # output$comparison_graph <- renderPlot({
      #   create_compare_graph(explor)
      # })
    })
  }

  runGadget(ui, server)
}

create_ui_gadget()

# shinyApp(ui, server, options = list(height = 700))
```
