---
output: 
  stevetemplates::article2:
    citation_package: natbib
    dev: cairo_pdf
    keep_tex: true
biblio-style: apsr
title: "litExplor: a systematic literature review tool"
thanks: "Replication files are available on the author's Github account (https://github.com/ransomts/ed_database_explor). **Current version**: `r format(Sys.time(), '%B %d, %Y')`; **Corresponding author**: tsranso@clemson.edu."
author:
- name: Tim Ransom
  affiliation: Clemson University
- name: Moss Gallagher
abstract: "Systematic literature reviews are a tedious process to undertake. Even experienced researchers have difficulty balancing the large numbers of decisions that must be made to produce a quality review. Frameworks like PRISMA have been developed by the research community to provide a roadmap for their production and to ensure quality. However, there is a major task at the beginning of such processes in deciding the proper search terms to query the literature for."
keywords: "pandoc, r markdown, knitr"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
mainfont: cochineal
#sansfont: Linux Biolinum O
fontsize: 11pt
doublespacing: TRUE
endnote: no
# pandocparas: TRUE
sansitup: FALSE
header-includes:
  - \usepackage{longtable}
  - \LTcapwidth=.95\textwidth
  - \linespread{1.05}
  - \usepackage{hyperref}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Uncomment below if you want code captions
# oldSource <- knitr::knit_hooks$get("source")
# knitr::knit_hooks$set(source = function(x, options) {
#   x <- oldSource(x, options)
#   x <- ifelse(!is.null(options$code.cap), paste0(x, "\\captionof{chunk}{", options$code.cap,"}"), x)
#   ifelse(!is.null(options$ref), paste0(x, "\\label{", options$ref,"}"), x)
# })
# Add `chunkcaption: TRUE` to YAML as well.
```



# Introduction

Systematic literature reviews require the researcher to decide search terms fairly early in the process. For the PRISMA framework, it is performed in the <insert number of step> step, early in the process. Other frameworks which are based on PRISMA such as JARS or PRISMA-P also require search term selection early in the process. 

The phrasing of this step varies across the frameworks, but data collection and selection is a critical if generic step in any research. 


# methods/development

FAVOR has been developed with a target audience of education researchers. The primary challenge of visualizing the data collected from the databases is in maintaining a reasonable cognitive load for the user. 

While researchers experienced in the field that they are producing a systematic literature review in are likely able to differentiate related terms in a literature base, novice researchers might struggle with this task. 
Specific terms relevant to a topic may have been updated, made more precise, or redefined entirely. 
Geographic factors have a large impact on the meanings of words as well. For example, in the United Kingdom, a polytechnical institution is an outdated term that is roughly comparable to American community college. 
FAVOR has an option to filter search results to ERIC supported geographic regions such as England or the United States.

# results/screenshots/walkthrough

## Breakdown of options

# Case studies

We demonstrate a sample workflow of our tool with two case studies. 
An aviation topic has  possibly less relevant or extraneous terms which are identified for removal. 
A topic of computing identity is selected to demonstrate identification of possible terms for refinement.

## Online aviation education

## Computing Identity

# discussion

## threats to validity

## future directions

As this work is targeting education researchers, ERIC is currently the only database being utilized. We make use of the official API to comply with resource usage restrictions, but this has a dual effect of opening our tool for other APIs. Interfaces to databases are commonly provided by other databases such as ProQuest, ScienceDirect, and ...


# acknowledgements
We would like to acknowledge the insight provided to this work by Dr. Eliza Gallagher and the faculty of the Clemson University Engineering and Science Education department as we have built and tuned this tool.

